name: food_allergy_scanner
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.2
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  pluralize: ^0.0.8
  http: ^1.2.2
  string_similarity: ^2.0.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add this section to include the .env file as an asset
  assets:
    - .env
